package com.inversionadvisor.domain.model

/**
 * Universo de mercado del screener: una pestaña por cada uno. Un mismo
 * símbolo puede pertenecer a varios (p. ej. AAPL está en S&P 500 y en
 * Nasdaq-100 a la vez), así que se escanea y se etiqueta por separado en
 * cada universo al que pertenece.
 */
enum class MarketUniverse(val indexName: String, val displayName: String) {
    SP500("SP500", "S&P 500"),
    NASDAQ100("NASDAQ100", "Nasdaq-100"),
    IBEX35("IBEX35", "IBEX 35"),
    /** Solo gráfica + volumen (ver IndexOverviewChartCard), SIN "Analizar" — no hay una fuente
     *  fiable con la lista completa de sus ~2000 constituyentes, a diferencia de los otros 3
     *  (Wikipedia no tiene tabla de constituyentes para este índice). */
    RUSSELL2000("RUSSELL2000", "Russell 2000"),
    /** Solo gráficas (varias, ver Symbols.CURRENCY_CHART_SYMBOLS) — no es un universo de
     *  acciones que escanear, así que tampoco tiene "Analizar" ni listas. */
    DIVISAS("DIVISAS", "Divisas"),
    /** Igual que DIVISAS, ver Symbols.US_BOND_CHART_SYMBOLS. */
    BONOS("BONOS", "Bonos USA"),
    /** Las 10 mejores acciones para invertir combinando SP500+NASDAQ100+IBEX35 — ver
     *  Top10Repository/Top10Calculator. No tiene universo propio que escanear (no cuenta con
     *  "Analizar" tampoco): depende de que esos 3 ya se hayan analizado antes. */
    TOP10("TOP10", "Top 10")
}

/**
 * Un stock del universo escaneado por el screener, con el ETF sectorial al
 * que se le asigna (para poder cruzar con la rotación sectorial ya
 * calculada y saber si está "en un sector en auge") y el índice/mercado al
 * que pertenece esta entrada concreta (StockUniverse.MarketUniverse.indexName).
 */
data class StockUniverseEntry(
    val symbol: String,
    val name: String,
    val sectorEtf: String,
    // Se rellena con .copy(indexName = ...) al construir cada lista de StockUniverse
    // (ver SP500/IBEX35 más abajo), para no tener que tocar cada literal.
    val indexName: String = ""
)

/**
 * Universo de RESPALDO del screener (foto fija), usado por
 * StockUniverseRepository solo si la auto-actualización desde Wikipedia
 * falla en el primer intento (sin red, cambio de formato de la página...).
 * En condiciones normales el screener usa la lista en vivo (S&P 500,
 * Nasdaq-100 e IBEX 35), no esta.
 *
 * Componentes del S&P 500 (503 valores, datos de GICS Sector vía
 * github.com/datasets/s-and-p-500-companies) + IBEX 35 (35 valores,
 * Wikipedia). Los tickers están en formato Yahoo Finance (BRK.B -> BRK-B;
 * sufijo .MC para las cotizadas en Madrid).
 */
object StockUniverse {

    private val rawSp500: List<StockUniverseEntry> = listOf(
    StockUniverseEntry("MMM", "3M", "XLI"),
    StockUniverseEntry("AOS", "A. O. Smith", "XLI"),
    StockUniverseEntry("ABT", "Abbott Laboratories", "XLV"),
    StockUniverseEntry("ABBV", "AbbVie", "XLV"),
    StockUniverseEntry("ACN", "Accenture", "XLK"),
    StockUniverseEntry("ADBE", "Adobe Inc.", "XLK"),
    StockUniverseEntry("AMD", "Advanced Micro Devices", "SMH"),
    StockUniverseEntry("AES", "AES Corporation", "XLU"),
    StockUniverseEntry("AFL", "Aflac", "XLF"),
    StockUniverseEntry("A", "Agilent Technologies", "XLV"),
    StockUniverseEntry("APD", "Air Products", "XLB"),
    StockUniverseEntry("ABNB", "Airbnb", "XLY"),
    StockUniverseEntry("AKAM", "Akamai Technologies", "XLK"),
    StockUniverseEntry("ALB", "Albemarle Corporation", "XLB"),
    StockUniverseEntry("ARE", "Alexandria Real Estate Equities", "XLRE"),
    StockUniverseEntry("ALGN", "Align Technology", "XLV"),
    StockUniverseEntry("ALLE", "Allegion", "XLI"),
    StockUniverseEntry("LNT", "Alliant Energy", "XLU"),
    StockUniverseEntry("ALL", "Allstate", "XLF"),
    StockUniverseEntry("GOOGL", "Alphabet Inc. (Class A)", "XLC"),
    StockUniverseEntry("GOOG", "Alphabet Inc. (Class C)", "XLC"),
    StockUniverseEntry("MO", "Altria", "XLP"),
    StockUniverseEntry("AMZN", "Amazon", "XLY"),
    StockUniverseEntry("AMCR", "Amcor", "XLB"),
    StockUniverseEntry("AEE", "Ameren", "XLU"),
    StockUniverseEntry("AEP", "American Electric Power", "XLU"),
    StockUniverseEntry("AXP", "American Express", "XLF"),
    StockUniverseEntry("AIG", "American International Group", "XLF"),
    StockUniverseEntry("AMT", "American Tower", "XLRE"),
    StockUniverseEntry("AWK", "American Water Works", "XLU"),
    StockUniverseEntry("AMP", "Ameriprise Financial", "XLF"),
    StockUniverseEntry("AME", "Ametek", "XLI"),
    StockUniverseEntry("AMGN", "Amgen", "XLV"),
    StockUniverseEntry("APH", "Amphenol", "XLK"),
    StockUniverseEntry("ADI", "Analog Devices", "SMH"),
    StockUniverseEntry("AON", "Aon plc", "XLF"),
    StockUniverseEntry("APA", "APA Corporation", "XLE"),
    StockUniverseEntry("APO", "Apollo Global Management", "XLF"),
    StockUniverseEntry("AAPL", "Apple Inc.", "XLK"),
    StockUniverseEntry("AMAT", "Applied Materials", "SMH"),
    StockUniverseEntry("APP", "AppLovin", "XLC"),
    StockUniverseEntry("APTV", "Aptiv", "XLY"),
    StockUniverseEntry("ACGL", "Arch Capital Group", "XLF"),
    StockUniverseEntry("ADM", "Archer Daniels Midland", "XLP"),
    StockUniverseEntry("ARES", "Ares Management", "XLF"),
    StockUniverseEntry("ANET", "Arista Networks", "XLK"),
    StockUniverseEntry("AJG", "Arthur J. Gallagher & Co.", "XLF"),
    StockUniverseEntry("AIZ", "Assurant", "XLF"),
    StockUniverseEntry("T", "AT&T", "XLC"),
    StockUniverseEntry("ATO", "Atmos Energy", "XLU"),
    StockUniverseEntry("ADSK", "Autodesk", "XLK"),
    StockUniverseEntry("ADP", "Automatic Data Processing", "XLI"),
    StockUniverseEntry("AZO", "AutoZone", "XLY"),
    StockUniverseEntry("AVB", "AvalonBay Communities", "XLRE"),
    StockUniverseEntry("AVY", "Avery Dennison", "XLB"),
    StockUniverseEntry("AXON", "Axon Enterprise", "ITA"),
    StockUniverseEntry("BKR", "Baker Hughes", "XLE"),
    StockUniverseEntry("BALL", "Ball Corporation", "XLB"),
    StockUniverseEntry("BAC", "Bank of America", "XLF"),
    StockUniverseEntry("BAX", "Baxter International", "XLV"),
    StockUniverseEntry("BDX", "Becton Dickinson", "XLV"),
    StockUniverseEntry("BRK-B", "Berkshire Hathaway", "XLF"),
    StockUniverseEntry("BBY", "Best Buy", "XLY"),
    StockUniverseEntry("TECH", "Bio-Techne", "XLV"),
    StockUniverseEntry("BIIB", "Biogen", "XLV"),
    StockUniverseEntry("BLK", "BlackRock", "XLF"),
    StockUniverseEntry("BX", "Blackstone Inc.", "XLF"),
    StockUniverseEntry("XYZ", "Block, Inc.", "XLF"),
    StockUniverseEntry("BNY", "BNY Mellon", "XLF"),
    StockUniverseEntry("BA", "Boeing", "ITA"),
    StockUniverseEntry("BKNG", "Booking Holdings", "XLY"),
    StockUniverseEntry("BSX", "Boston Scientific", "XLV"),
    StockUniverseEntry("BMY", "Bristol Myers Squibb", "XLV"),
    StockUniverseEntry("AVGO", "Broadcom", "SMH"),
    StockUniverseEntry("BR", "Broadridge Financial Solutions", "XLI"),
    StockUniverseEntry("BRO", "Brown & Brown", "XLF"),
    StockUniverseEntry("BF-B", "Brown–Forman", "XLP"),
    StockUniverseEntry("BLDR", "Builders FirstSource", "XLI"),
    StockUniverseEntry("BG", "Bunge Global", "XLP"),
    StockUniverseEntry("BXP", "BXP, Inc.", "XLRE"),
    StockUniverseEntry("CHRW", "C.H. Robinson", "XLI"),
    StockUniverseEntry("CDNS", "Cadence Design Systems", "XLK"),
    StockUniverseEntry("CPT", "Camden Property Trust", "XLRE"),
    StockUniverseEntry("COF", "Capital One", "XLF"),
    StockUniverseEntry("CAH", "Cardinal Health", "XLV"),
    StockUniverseEntry("CCL", "Carnival Corporation", "XLY"),
    StockUniverseEntry("CARR", "Carrier Global", "XLI"),
    StockUniverseEntry("CVNA", "Carvana", "XLY"),
    StockUniverseEntry("CASY", "Casey's", "XLP"),
    StockUniverseEntry("CAT", "Caterpillar Inc.", "XLI"),
    StockUniverseEntry("CBOE", "Cboe Global Markets", "XLF"),
    StockUniverseEntry("CBRE", "CBRE Group", "XLRE"),
    StockUniverseEntry("CDW", "CDW Corporation", "XLK"),
    StockUniverseEntry("COR", "Cencora", "XLV"),
    StockUniverseEntry("CNC", "Centene Corporation", "XLV"),
    StockUniverseEntry("CNP", "CenterPoint Energy", "XLU"),
    StockUniverseEntry("CF", "CF Industries", "XLB"),
    StockUniverseEntry("CRL", "Charles River Laboratories", "XLV"),
    StockUniverseEntry("SCHW", "Charles Schwab Corporation", "XLF"),
    StockUniverseEntry("CHTR", "Charter Communications", "XLC"),
    StockUniverseEntry("CVX", "Chevron Corporation", "XLE"),
    StockUniverseEntry("CMG", "Chipotle Mexican Grill", "XLY"),
    StockUniverseEntry("CB", "Chubb Limited", "XLF"),
    StockUniverseEntry("CHD", "Church & Dwight", "XLP"),
    StockUniverseEntry("CIEN", "Ciena", "XLK"),
    StockUniverseEntry("CI", "Cigna", "XLV"),
    StockUniverseEntry("CINF", "Cincinnati Financial", "XLF"),
    StockUniverseEntry("CTAS", "Cintas", "XLI"),
    StockUniverseEntry("CSCO", "Cisco", "XLK"),
    StockUniverseEntry("C", "Citigroup", "XLF"),
    StockUniverseEntry("CFG", "Citizens Financial Group", "XLF"),
    StockUniverseEntry("CLX", "Clorox", "XLP"),
    StockUniverseEntry("CME", "CME Group", "XLF"),
    StockUniverseEntry("CMS", "CMS Energy", "XLU"),
    StockUniverseEntry("KO", "Coca-Cola Company (The)", "XLP"),
    StockUniverseEntry("CTSH", "Cognizant", "XLK"),
    StockUniverseEntry("COHR", "Coherent Corp.", "XLK"),
    StockUniverseEntry("COIN", "Coinbase", "XLF"),
    StockUniverseEntry("CL", "Colgate-Palmolive", "XLP"),
    StockUniverseEntry("CMCSA", "Comcast", "XLC"),
    StockUniverseEntry("FIX", "Comfort Systems USA", "XLI"),
    StockUniverseEntry("COP", "ConocoPhillips", "XLE"),
    StockUniverseEntry("ED", "Consolidated Edison", "XLU"),
    StockUniverseEntry("STZ", "Constellation Brands", "XLP"),
    StockUniverseEntry("CEG", "Constellation Energy", "XLU"),
    StockUniverseEntry("COO", "Cooper Companies (The)", "XLV"),
    StockUniverseEntry("CPRT", "Copart", "XLI"),
    StockUniverseEntry("GLW", "Corning Inc.", "XLK"),
    StockUniverseEntry("CPAY", "Corpay", "XLF"),
    StockUniverseEntry("CTVA", "Corteva", "XLB"),
    StockUniverseEntry("CSGP", "CoStar Group", "XLRE"),
    StockUniverseEntry("COST", "Costco", "XLP"),
    StockUniverseEntry("CRH", "CRH plc", "XLB"),
    StockUniverseEntry("CRWD", "CrowdStrike", "XLK"),
    StockUniverseEntry("CCI", "Crown Castle", "XLRE"),
    StockUniverseEntry("CSX", "CSX Corporation", "XLI"),
    StockUniverseEntry("CMI", "Cummins", "XLI"),
    StockUniverseEntry("CVS", "CVS Health", "XLV"),
    StockUniverseEntry("DHR", "Danaher Corporation", "XLV"),
    StockUniverseEntry("DRI", "Darden Restaurants", "XLY"),
    StockUniverseEntry("DDOG", "Datadog", "XLK"),
    StockUniverseEntry("DVA", "DaVita", "XLV"),
    StockUniverseEntry("DECK", "Deckers Brands", "XLY"),
    StockUniverseEntry("DE", "Deere & Company", "XLI"),
    StockUniverseEntry("DELL", "Dell Technologies", "XLK"),
    StockUniverseEntry("DAL", "Delta Air Lines", "XLI"),
    StockUniverseEntry("DVN", "Devon Energy", "XLE"),
    StockUniverseEntry("DXCM", "Dexcom", "XLV"),
    StockUniverseEntry("FANG", "Diamondback Energy", "XLE"),
    StockUniverseEntry("DLR", "Digital Realty", "XLRE"),
    StockUniverseEntry("DG", "Dollar General", "XLP"),
    StockUniverseEntry("DLTR", "Dollar Tree", "XLP"),
    StockUniverseEntry("D", "Dominion Energy", "XLU"),
    StockUniverseEntry("DPZ", "Domino's", "XLY"),
    StockUniverseEntry("DASH", "DoorDash", "XLY"),
    StockUniverseEntry("DOV", "Dover Corporation", "XLI"),
    StockUniverseEntry("DOW", "Dow Inc.", "XLB"),
    StockUniverseEntry("DHI", "D. R. Horton", "XLY"),
    StockUniverseEntry("DTE", "DTE Energy", "XLU"),
    StockUniverseEntry("DUK", "Duke Energy", "XLU"),
    StockUniverseEntry("DD", "DuPont", "XLI"),
    StockUniverseEntry("ETN", "Eaton Corporation", "XLI"),
    StockUniverseEntry("EBAY", "eBay Inc.", "XLY"),
    StockUniverseEntry("ECHO", "EchoStar", "XLC"),
    StockUniverseEntry("ECL", "Ecolab", "XLB"),
    StockUniverseEntry("EIX", "Edison International", "XLU"),
    StockUniverseEntry("EW", "Edwards Lifesciences", "XLV"),
    StockUniverseEntry("ELV", "Elevance Health", "XLV"),
    StockUniverseEntry("EME", "Emcor", "XLI"),
    StockUniverseEntry("EMR", "Emerson Electric", "XLI"),
    StockUniverseEntry("ETR", "Entergy", "XLU"),
    StockUniverseEntry("EOG", "EOG Resources", "XLE"),
    StockUniverseEntry("EQT", "EQT Corporation", "XLE"),
    StockUniverseEntry("EFX", "Equifax", "XLI"),
    StockUniverseEntry("EQIX", "Equinix", "XLRE"),
    StockUniverseEntry("EQR", "Equity Residential", "XLRE"),
    StockUniverseEntry("ERIE", "Erie Indemnity", "XLF"),
    StockUniverseEntry("ESS", "Essex Property Trust", "XLRE"),
    StockUniverseEntry("EL", "Estée Lauder Companies (The)", "XLP"),
    StockUniverseEntry("EG", "Everest Group", "XLF"),
    StockUniverseEntry("EVRG", "Evergy", "XLU"),
    StockUniverseEntry("ES", "Eversource Energy", "XLU"),
    StockUniverseEntry("EXC", "Exelon", "XLU"),
    StockUniverseEntry("EXE", "Expand Energy", "XLE"),
    StockUniverseEntry("EXPE", "Expedia Group", "XLY"),
    StockUniverseEntry("EXPD", "Expeditors International", "XLI"),
    StockUniverseEntry("EXR", "Extra Space Storage", "XLRE"),
    StockUniverseEntry("XOM", "ExxonMobil", "XLE"),
    StockUniverseEntry("FFIV", "F5, Inc.", "XLK"),
    StockUniverseEntry("FDS", "FactSet", "XLF"),
    StockUniverseEntry("FICO", "Fair Isaac", "XLK"),
    StockUniverseEntry("FAST", "Fastenal", "XLI"),
    StockUniverseEntry("FRT", "Federal Realty Investment Trust", "XLRE"),
    StockUniverseEntry("FDX", "FedEx", "XLI"),
    StockUniverseEntry("FDXF", "FedEx Freight", "XLI"),
    StockUniverseEntry("FERG", "Ferguson Enterprises", "XLI"),
    StockUniverseEntry("FIS", "Fidelity National Information Services", "XLF"),
    StockUniverseEntry("FITB", "Fifth Third Bancorp", "XLF"),
    StockUniverseEntry("FSLR", "First Solar", "SMH"),
    StockUniverseEntry("FE", "FirstEnergy", "XLU"),
    StockUniverseEntry("FISV", "Fiserv", "XLF"),
    StockUniverseEntry("FLEX", "Flex Ltd.", "XLK"),
    StockUniverseEntry("F", "Ford Motor Company", "XLY"),
    StockUniverseEntry("FTNT", "Fortinet", "XLK"),
    StockUniverseEntry("FTV", "Fortive", "XLI"),
    StockUniverseEntry("FOXA", "Fox Corporation (Class A)", "XLC"),
    StockUniverseEntry("FOX", "Fox Corporation (Class B)", "XLC"),
    StockUniverseEntry("BEN", "Franklin Resources", "XLF"),
    StockUniverseEntry("FCX", "Freeport-McMoRan", "XLB"),
    StockUniverseEntry("GRMN", "Garmin", "XLY"),
    StockUniverseEntry("IT", "Gartner", "XLK"),
    StockUniverseEntry("GE", "GE Aerospace", "ITA"),
    StockUniverseEntry("GEHC", "GE HealthCare", "XLV"),
    StockUniverseEntry("GEV", "GE Vernova", "XLI"),
    StockUniverseEntry("GEN", "Gen Digital", "XLK"),
    StockUniverseEntry("GNRC", "Generac", "XLI"),
    StockUniverseEntry("GD", "General Dynamics", "ITA"),
    StockUniverseEntry("GIS", "General Mills", "XLP"),
    StockUniverseEntry("GM", "General Motors", "XLY"),
    StockUniverseEntry("GPC", "Genuine Parts Company", "XLY"),
    StockUniverseEntry("GILD", "Gilead Sciences", "XLV"),
    StockUniverseEntry("GPN", "Global Payments", "XLF"),
    StockUniverseEntry("GL", "Globe Life", "XLF"),
    StockUniverseEntry("GDDY", "GoDaddy", "XLK"),
    StockUniverseEntry("GS", "Goldman Sachs", "XLF"),
    StockUniverseEntry("HAL", "Halliburton", "XLE"),
    StockUniverseEntry("HIG", "Hartford (The)", "XLF"),
    StockUniverseEntry("HAS", "Hasbro", "XLY"),
    StockUniverseEntry("HCA", "HCA Healthcare", "XLV"),
    StockUniverseEntry("DOC", "Healthpeak Properties", "XLRE"),
    StockUniverseEntry("HSIC", "Henry Schein", "XLV"),
    StockUniverseEntry("HSY", "Hershey Company (The)", "XLP"),
    StockUniverseEntry("HPE", "Hewlett Packard Enterprise", "XLK"),
    StockUniverseEntry("HLT", "Hilton Worldwide", "XLY"),
    StockUniverseEntry("HD", "Home Depot (The)", "XLY"),
    StockUniverseEntry("HONA", "Honeywell Aerospace", "ITA"),
    StockUniverseEntry("HON", "Honeywell Technologies", "XLI"),
    StockUniverseEntry("HRL", "Hormel Foods", "XLP"),
    StockUniverseEntry("HST", "Host Hotels & Resorts", "XLRE"),
    StockUniverseEntry("HWM", "Howmet Aerospace", "ITA"),
    StockUniverseEntry("HPQ", "HP Inc.", "XLK"),
    StockUniverseEntry("HUBB", "Hubbell Incorporated", "XLI"),
    StockUniverseEntry("HUM", "Humana", "XLV"),
    StockUniverseEntry("HBAN", "Huntington Bancshares", "XLF"),
    StockUniverseEntry("HII", "Huntington Ingalls Industries", "ITA"),
    StockUniverseEntry("IBM", "IBM", "XLK"),
    StockUniverseEntry("IEX", "IDEX Corporation", "XLI"),
    StockUniverseEntry("IDXX", "Idexx Laboratories", "XLV"),
    StockUniverseEntry("ITW", "Illinois Tool Works", "XLI"),
    StockUniverseEntry("INCY", "Incyte", "XLV"),
    StockUniverseEntry("IR", "Ingersoll Rand", "XLI"),
    StockUniverseEntry("PODD", "Insulet Corporation", "XLV"),
    StockUniverseEntry("INTC", "Intel", "SMH"),
    StockUniverseEntry("IBKR", "Interactive Brokers", "XLF"),
    StockUniverseEntry("ICE", "Intercontinental Exchange", "XLF"),
    StockUniverseEntry("IFF", "International Flavors & Fragrances", "XLB"),
    StockUniverseEntry("IP", "International Paper", "XLB"),
    StockUniverseEntry("INTU", "Intuit", "XLK"),
    StockUniverseEntry("ISRG", "Intuitive Surgical", "XLV"),
    StockUniverseEntry("IVZ", "Invesco", "XLF"),
    StockUniverseEntry("INVH", "Invitation Homes", "XLRE"),
    StockUniverseEntry("IQV", "IQVIA", "XLV"),
    StockUniverseEntry("IRM", "Iron Mountain", "XLRE"),
    StockUniverseEntry("JBHT", "J.B. Hunt", "XLI"),
    StockUniverseEntry("JBL", "Jabil", "XLK"),
    StockUniverseEntry("JKHY", "Jack Henry & Associates", "XLF"),
    StockUniverseEntry("J", "Jacobs Solutions", "XLI"),
    StockUniverseEntry("JNJ", "Johnson & Johnson", "XLV"),
    StockUniverseEntry("JCI", "Johnson Controls", "XLI"),
    StockUniverseEntry("JPM", "JPMorgan Chase", "XLF"),
    StockUniverseEntry("KVUE", "Kenvue", "XLP"),
    StockUniverseEntry("KDP", "Keurig Dr Pepper", "XLP"),
    StockUniverseEntry("KEY", "KeyCorp", "XLF"),
    StockUniverseEntry("KEYS", "Keysight Technologies", "XLK"),
    StockUniverseEntry("KMB", "Kimberly-Clark", "XLP"),
    StockUniverseEntry("KIM", "Kimco Realty", "XLRE"),
    StockUniverseEntry("KMI", "Kinder Morgan", "XLE"),
    StockUniverseEntry("KKR", "KKR & Co.", "XLF"),
    StockUniverseEntry("KLAC", "KLA Corporation", "SMH"),
    StockUniverseEntry("KHC", "Kraft Heinz", "XLP"),
    StockUniverseEntry("KR", "Kroger", "XLP"),
    StockUniverseEntry("LHX", "L3Harris", "ITA"),
    StockUniverseEntry("LH", "Labcorp", "XLV"),
    StockUniverseEntry("LRCX", "Lam Research", "SMH"),
    StockUniverseEntry("LVS", "Las Vegas Sands", "XLY"),
    StockUniverseEntry("LDOS", "Leidos", "XLI"),
    StockUniverseEntry("LEN", "Lennar", "XLY"),
    StockUniverseEntry("LII", "Lennox International", "XLI"),
    StockUniverseEntry("LLY", "Lilly (Eli)", "XLV"),
    StockUniverseEntry("LIN", "Linde plc", "XLB"),
    StockUniverseEntry("LYV", "Live Nation Entertainment", "XLC"),
    StockUniverseEntry("LMT", "Lockheed Martin", "ITA"),
    StockUniverseEntry("L", "Loews Corporation", "XLF"),
    StockUniverseEntry("LOW", "Lowe's", "XLY"),
    StockUniverseEntry("LULU", "Lululemon Athletica", "XLY"),
    StockUniverseEntry("LITE", "Lumentum", "XLK"),
    StockUniverseEntry("LYB", "LyondellBasell", "XLB"),
    StockUniverseEntry("MTB", "M&T Bank", "XLF"),
    StockUniverseEntry("MPC", "Marathon Petroleum", "XLE"),
    StockUniverseEntry("MAR", "Marriott International", "XLY"),
    StockUniverseEntry("MRSH", "Marsh McLennan", "XLF"),
    StockUniverseEntry("MLM", "Martin Marietta Materials", "XLB"),
    StockUniverseEntry("MRVL", "Marvell Technology", "SMH"),
    StockUniverseEntry("MAS", "Masco", "XLI"),
    StockUniverseEntry("MA", "Mastercard", "XLF"),
    StockUniverseEntry("MKC", "McCormick & Company", "XLP"),
    StockUniverseEntry("MCD", "McDonald's", "XLY"),
    StockUniverseEntry("MCK", "McKesson Corporation", "XLV"),
    StockUniverseEntry("MDT", "Medtronic", "XLV"),
    StockUniverseEntry("MRK", "Merck & Co.", "XLV"),
    StockUniverseEntry("META", "Meta Platforms", "XLC"),
    StockUniverseEntry("MET", "MetLife", "XLF"),
    StockUniverseEntry("MTD", "Mettler Toledo", "XLV"),
    StockUniverseEntry("MGM", "MGM Resorts", "XLY"),
    StockUniverseEntry("MCHP", "Microchip Technology", "SMH"),
    StockUniverseEntry("MU", "Micron Technology", "SMH"),
    StockUniverseEntry("MSFT", "Microsoft", "XLK"),
    StockUniverseEntry("MAA", "Mid-America Apartment Communities", "XLRE"),
    StockUniverseEntry("MRNA", "Moderna", "XLV"),
    StockUniverseEntry("TAP", "Molson Coors Beverage Company", "XLP"),
    StockUniverseEntry("MDLZ", "Mondelez International", "XLP"),
    StockUniverseEntry("MPWR", "Monolithic Power Systems", "SMH"),
    StockUniverseEntry("MNST", "Monster Beverage", "XLP"),
    StockUniverseEntry("MCO", "Moody's Corporation", "XLF"),
    StockUniverseEntry("MS", "Morgan Stanley", "XLF"),
    StockUniverseEntry("MOS", "Mosaic Company (The)", "XLB"),
    StockUniverseEntry("MSI", "Motorola Solutions", "XLK"),
    StockUniverseEntry("MSCI", "MSCI", "XLF"),
    StockUniverseEntry("NDAQ", "Nasdaq, Inc.", "XLF"),
    StockUniverseEntry("NTAP", "NetApp", "XLK"),
    StockUniverseEntry("NFLX", "Netflix", "XLC"),
    StockUniverseEntry("NEM", "Newmont", "XLB"),
    StockUniverseEntry("NWSA", "News Corp (Class A)", "XLC"),
    StockUniverseEntry("NWS", "News Corp (Class B)", "XLC"),
    StockUniverseEntry("NEE", "NextEra Energy", "XLU"),
    StockUniverseEntry("NKE", "Nike, Inc.", "XLY"),
    StockUniverseEntry("NI", "NiSource", "XLU"),
    StockUniverseEntry("NDSN", "Nordson Corporation", "XLI"),
    StockUniverseEntry("NSC", "Norfolk Southern", "XLI"),
    StockUniverseEntry("NTRS", "Northern Trust", "XLF"),
    StockUniverseEntry("NOC", "Northrop Grumman", "ITA"),
    StockUniverseEntry("NCLH", "Norwegian Cruise Line Holdings", "XLY"),
    StockUniverseEntry("NRG", "NRG Energy", "XLU"),
    StockUniverseEntry("NUE", "Nucor", "XLB"),
    StockUniverseEntry("NVDA", "Nvidia", "SMH"),
    StockUniverseEntry("NVR", "NVR, Inc.", "XLY"),
    StockUniverseEntry("NXPI", "NXP Semiconductors", "SMH"),
    StockUniverseEntry("ORLY", "O'Reilly Automotive", "XLY"),
    StockUniverseEntry("OXY", "Occidental Petroleum", "XLE"),
    StockUniverseEntry("ODFL", "Old Dominion", "XLI"),
    StockUniverseEntry("OMC", "Omnicom Group", "XLC"),
    StockUniverseEntry("ON", "ON Semiconductor", "SMH"),
    StockUniverseEntry("OKE", "Oneok", "XLE"),
    StockUniverseEntry("ORCL", "Oracle Corporation", "XLK"),
    StockUniverseEntry("OTIS", "Otis Worldwide", "XLI"),
    StockUniverseEntry("PCAR", "Paccar", "XLI"),
    StockUniverseEntry("PKG", "Packaging Corporation of America", "XLB"),
    StockUniverseEntry("PLTR", "Palantir Technologies", "XLK"),
    StockUniverseEntry("PANW", "Palo Alto Networks", "XLK"),
    StockUniverseEntry("PSKY", "Paramount Skydance Corporation", "XLC"),
    StockUniverseEntry("PH", "Parker Hannifin", "XLI"),
    StockUniverseEntry("PAYX", "Paychex", "XLI"),
    StockUniverseEntry("PYPL", "PayPal", "XLF"),
    StockUniverseEntry("PNR", "Pentair", "XLI"),
    StockUniverseEntry("PEP", "PepsiCo", "XLP"),
    StockUniverseEntry("PFE", "Pfizer", "XLV"),
    StockUniverseEntry("PCG", "PG&E Corporation", "XLU"),
    StockUniverseEntry("PM", "Philip Morris International", "XLP"),
    StockUniverseEntry("PSX", "Phillips 66", "XLE"),
    StockUniverseEntry("PNW", "Pinnacle West Capital", "XLU"),
    StockUniverseEntry("PNC", "PNC Financial Services", "XLF"),
    StockUniverseEntry("PPG", "PPG Industries", "XLB"),
    StockUniverseEntry("PPL", "PPL Corporation", "XLU"),
    StockUniverseEntry("PFG", "Principal Financial Group", "XLF"),
    StockUniverseEntry("PG", "Procter & Gamble", "XLP"),
    StockUniverseEntry("PGR", "Progressive Corporation", "XLF"),
    StockUniverseEntry("PLD", "Prologis", "XLRE"),
    StockUniverseEntry("PRU", "Prudential Financial", "XLF"),
    StockUniverseEntry("PEG", "Public Service Enterprise Group", "XLU"),
    StockUniverseEntry("PTC", "PTC Inc.", "XLK"),
    StockUniverseEntry("PSA", "Public Storage", "XLRE"),
    StockUniverseEntry("PHM", "PulteGroup", "XLY"),
    StockUniverseEntry("PWR", "Quanta Services", "XLI"),
    StockUniverseEntry("QCOM", "Qualcomm", "SMH"),
    StockUniverseEntry("DGX", "Quest Diagnostics", "XLV"),
    StockUniverseEntry("Q", "Qnity Electronics", "SMH"),
    StockUniverseEntry("RL", "Ralph Lauren Corporation", "XLY"),
    StockUniverseEntry("RJF", "Raymond James Financial", "XLF"),
    StockUniverseEntry("RTX", "RTX Corporation", "ITA"),
    StockUniverseEntry("O", "Realty Income", "XLRE"),
    StockUniverseEntry("REG", "Regency Centers", "XLRE"),
    StockUniverseEntry("REGN", "Regeneron Pharmaceuticals", "XLV"),
    StockUniverseEntry("RF", "Regions Financial Corporation", "XLF"),
    StockUniverseEntry("RSG", "Republic Services", "XLI"),
    StockUniverseEntry("RMD", "ResMed|", "XLV"),
    StockUniverseEntry("RVTY", "Revvity", "XLV"),
    StockUniverseEntry("HOOD", "Robinhood Markets", "XLF"),
    StockUniverseEntry("ROK", "Rockwell Automation", "XLI"),
    StockUniverseEntry("ROL", "Rollins, Inc.", "XLI"),
    StockUniverseEntry("ROP", "Roper Technologies", "XLK"),
    StockUniverseEntry("ROST", "Ross Stores", "XLY"),
    StockUniverseEntry("RCL", "Royal Caribbean Group", "XLY"),
    StockUniverseEntry("SPGI", "S&P Global", "XLF"),
    StockUniverseEntry("CRM", "Salesforce", "XLK"),
    StockUniverseEntry("SNDK", "Sandisk", "XLK"),
    StockUniverseEntry("SBAC", "SBA Communications", "XLRE"),
    StockUniverseEntry("SLB", "Schlumberger", "XLE"),
    StockUniverseEntry("STX", "Seagate Technology", "XLK"),
    StockUniverseEntry("SRE", "Sempra", "XLU"),
    StockUniverseEntry("NOW", "ServiceNow", "XLK"),
    StockUniverseEntry("SHW", "Sherwin-Williams", "XLB"),
    StockUniverseEntry("SPG", "Simon Property Group", "XLRE"),
    StockUniverseEntry("SWKS", "Skyworks Solutions", "SMH"),
    StockUniverseEntry("SJM", "J.M. Smucker Company (The)", "XLP"),
    StockUniverseEntry("SW", "Smurfit Westrock", "XLB"),
    StockUniverseEntry("SNA", "Snap-on", "XLI"),
    StockUniverseEntry("SOLV", "Solventum", "XLV"),
    StockUniverseEntry("SO", "Southern Company", "XLU"),
    StockUniverseEntry("LUV", "Southwest Airlines", "XLI"),
    StockUniverseEntry("SWK", "Stanley Black & Decker", "XLI"),
    StockUniverseEntry("SBUX", "Starbucks", "XLY"),
    StockUniverseEntry("STT", "State Street Corporation", "XLF"),
    StockUniverseEntry("STLD", "Steel Dynamics", "XLB"),
    StockUniverseEntry("STE", "Steris", "XLV"),
    StockUniverseEntry("SYK", "Stryker Corporation", "XLV"),
    StockUniverseEntry("SMCI", "Supermicro", "XLK"),
    StockUniverseEntry("SYF", "Synchrony Financial", "XLF"),
    StockUniverseEntry("SNPS", "Synopsys", "XLK"),
    StockUniverseEntry("SYY", "Sysco", "XLP"),
    StockUniverseEntry("TMUS", "T-Mobile US", "XLC"),
    StockUniverseEntry("TROW", "T. Rowe Price", "XLF"),
    StockUniverseEntry("TTWO", "Take-Two Interactive", "XLC"),
    StockUniverseEntry("TPR", "Tapestry, Inc.", "XLY"),
    StockUniverseEntry("TRGP", "Targa Resources", "XLE"),
    StockUniverseEntry("TGT", "Target Corporation", "XLP"),
    StockUniverseEntry("TEL", "TE Connectivity", "XLK"),
    StockUniverseEntry("TDY", "Teledyne Technologies", "XLK"),
    StockUniverseEntry("TER", "Teradyne", "SMH"),
    StockUniverseEntry("TSLA", "Tesla, Inc.", "XLY"),
    StockUniverseEntry("TXN", "Texas Instruments", "SMH"),
    StockUniverseEntry("TPL", "Texas Pacific Land Corporation", "XLE"),
    StockUniverseEntry("TXT", "Textron", "ITA"),
    StockUniverseEntry("TMO", "Thermo Fisher Scientific", "XLV"),
    StockUniverseEntry("TJX", "TJX Companies", "XLY"),
    StockUniverseEntry("TKO", "TKO Group Holdings", "XLC"),
    StockUniverseEntry("TTD", "Trade Desk (The)", "XLC"),
    StockUniverseEntry("TSCO", "Tractor Supply", "XLY"),
    StockUniverseEntry("TT", "Trane Technologies", "XLI"),
    StockUniverseEntry("TDG", "TransDigm Group", "ITA"),
    StockUniverseEntry("TRV", "Travelers Companies (The)", "XLF"),
    StockUniverseEntry("TRMB", "Trimble Inc.", "XLK"),
    StockUniverseEntry("TFC", "Truist Financial", "XLF"),
    StockUniverseEntry("TYL", "Tyler Technologies", "XLK"),
    StockUniverseEntry("TSN", "Tyson Foods", "XLP"),
    StockUniverseEntry("USB", "U.S. Bancorp", "XLF"),
    StockUniverseEntry("UBER", "Uber", "XLI"),
    StockUniverseEntry("UDR", "UDR, Inc.", "XLRE"),
    StockUniverseEntry("ULTA", "Ulta Beauty", "XLY"),
    StockUniverseEntry("UNP", "Union Pacific Corporation", "XLI"),
    StockUniverseEntry("UAL", "United Airlines Holdings", "XLI"),
    StockUniverseEntry("UPS", "United Parcel Service", "XLI"),
    StockUniverseEntry("URI", "United Rentals", "XLI"),
    StockUniverseEntry("UNH", "UnitedHealth Group", "XLV"),
    StockUniverseEntry("UHS", "Universal Health Services", "XLV"),
    StockUniverseEntry("VLO", "Valero Energy", "XLE"),
    StockUniverseEntry("VEEV", "Veeva Systems", "XLV"),
    StockUniverseEntry("VTR", "Ventas", "XLRE"),
    StockUniverseEntry("VLTO", "Veralto", "XLI"),
    StockUniverseEntry("VRSN", "Verisign", "XLK"),
    StockUniverseEntry("VRSK", "Verisk Analytics", "XLI"),
    StockUniverseEntry("VZ", "Verizon", "XLC"),
    StockUniverseEntry("VRTX", "Vertex Pharmaceuticals", "XLV"),
    StockUniverseEntry("VRT", "Vertiv", "XLI"),
    StockUniverseEntry("VTRS", "Viatris", "XLV"),
    StockUniverseEntry("VICI", "Vici Properties", "XLRE"),
    StockUniverseEntry("V", "Visa Inc.", "XLF"),
    StockUniverseEntry("VST", "Vistra Corp.", "XLU"),
    StockUniverseEntry("VMC", "Vulcan Materials Company", "XLB"),
    StockUniverseEntry("WRB", "W. R. Berkley Corporation", "XLF"),
    StockUniverseEntry("GWW", "W. W. Grainger", "XLI"),
    StockUniverseEntry("WAB", "Wabtec", "XLI"),
    StockUniverseEntry("WMT", "Walmart", "XLP"),
    StockUniverseEntry("DIS", "Walt Disney Company (The)", "XLC"),
    StockUniverseEntry("WBD", "Warner Bros. Discovery", "XLC"),
    StockUniverseEntry("WM", "Waste Management", "XLI"),
    StockUniverseEntry("WAT", "Waters Corporation", "XLV"),
    StockUniverseEntry("WEC", "WEC Energy Group", "XLU"),
    StockUniverseEntry("WFC", "Wells Fargo", "XLF"),
    StockUniverseEntry("WELL", "Welltower", "XLRE"),
    StockUniverseEntry("WST", "West Pharmaceutical Services", "XLV"),
    StockUniverseEntry("WDC", "Western Digital", "XLK"),
    StockUniverseEntry("WY", "Weyerhaeuser", "XLRE"),
    StockUniverseEntry("WSM", "Williams-Sonoma, Inc.", "XLY"),
    StockUniverseEntry("WMB", "Williams Companies", "XLE"),
    StockUniverseEntry("WTW", "Willis Towers Watson", "XLF"),
    StockUniverseEntry("WDAY", "Workday, Inc.", "XLK"),
    StockUniverseEntry("WYNN", "Wynn Resorts", "XLY"),
    StockUniverseEntry("XEL", "Xcel Energy", "XLU"),
    StockUniverseEntry("XYL", "Xylem Inc.", "XLI"),
    StockUniverseEntry("YUM", "Yum! Brands", "XLY"),
    StockUniverseEntry("ZBRA", "Zebra Technologies", "XLK"),
    StockUniverseEntry("ZBH", "Zimmer Biomet", "XLV"),
    StockUniverseEntry("ZTS", "Zoetis", "XLV"),
    )

    val SP500: List<StockUniverseEntry> = rawSp500.map { it.copy(indexName = MarketUniverse.SP500.indexName) }

    private val rawIbex35: List<StockUniverseEntry> = listOf(
    StockUniverseEntry("ACS.MC", "ACS", "XLI"),
    StockUniverseEntry("ACX.MC", "Acerinox", "XLB"),
    StockUniverseEntry("AMS.MC", "Amadeus IT Group", "XLY"),
    StockUniverseEntry("ANA.MC", "Acciona", "XLI"),
    StockUniverseEntry("ANE.MC", "Acciona Energía", "XLU"),
    StockUniverseEntry("BBVA.MC", "BBVA", "XLF"),
    StockUniverseEntry("BKT.MC", "Bankinter", "XLF"),
    StockUniverseEntry("CABK.MC", "CaixaBank", "XLF"),
    StockUniverseEntry("CLNX.MC", "Cellnex Telecom", "XLC"),
    StockUniverseEntry("COL.MC", "Inmobiliaria Colonial", "XLRE"),
    StockUniverseEntry("AENA.MC", "AENA", "XLI"),
    StockUniverseEntry("ELE.MC", "Endesa", "XLU"),
    StockUniverseEntry("ENG.MC", "Enagás", "XLU"),
    StockUniverseEntry("FDR.MC", "Fluidra", "XLI"),
    StockUniverseEntry("FER.MC", "Ferrovial", "XLI"),
    StockUniverseEntry("GRF.MC", "Grifols", "XLV"),
    StockUniverseEntry("IAG.MC", "International Airlines Group", "XLI"),
    StockUniverseEntry("IBE.MC", "Iberdrola", "XLU"),
    StockUniverseEntry("IDR.MC", "Indra", "XLK"),
    StockUniverseEntry("ITX.MC", "Inditex", "XLY"),
    StockUniverseEntry("LOG.MC", "Logista", "XLI"),
    StockUniverseEntry("MAP.MC", "Mapfre", "XLF"),
    StockUniverseEntry("MRL.MC", "Merlin Properties", "XLRE"),
    StockUniverseEntry("MTS.MC", "ArcelorMittal", "XLB"),
    StockUniverseEntry("NTGY.MC", "Naturgy", "XLU"),
    StockUniverseEntry("PUIG.MC", "Puig", "XLY"),
    StockUniverseEntry("RED.MC", "Redeia Corporación", "XLU"),
    StockUniverseEntry("REP.MC", "Repsol", "XLE"),
    StockUniverseEntry("ROVI.MC", "Laboratorios Rovi", "XLV"),
    StockUniverseEntry("SAB.MC", "Banco Sabadell", "XLF"),
    StockUniverseEntry("SAN.MC", "Banco Santander", "XLF"),
    StockUniverseEntry("SCYR.MC", "Sacyr", "XLI"),
    StockUniverseEntry("SLR.MC", "Solaria", "XLU"),
    StockUniverseEntry("TEF.MC", "Telefónica", "XLC"),
    StockUniverseEntry("UNI.MC", "Unicaja Banco", "XLF"),
    )

    val IBEX35: List<StockUniverseEntry> = rawIbex35.map { it.copy(indexName = MarketUniverse.IBEX35.indexName) }

    /**
     * Componentes del Nasdaq-100 (102 símbolos, incluye las dos clases de
     * Alphabet). A diferencia de SP500/IBEX35, esta es la fuente PRINCIPAL
     * del mercado, no solo un respaldo: la página de Wikipedia de sus
     * constituyentes ya no trae la tabla completa embebida (ver comentario
     * de StockUniverseRepository), así que en la práctica el screener
     * siempre usa esta lista para Nasdaq-100.
     */
    private val rawNasdaq100: List<StockUniverseEntry> = listOf(
    StockUniverseEntry("NVDA", "Nvidia", "SMH"),
    StockUniverseEntry("AAPL", "Apple Inc.", "XLK"),
    StockUniverseEntry("MSFT", "Microsoft", "XLK"),
    StockUniverseEntry("AMZN", "Amazon", "XLY"),
    StockUniverseEntry("GOOGL", "Alphabet Inc. (Class A)", "XLC"),
    StockUniverseEntry("GOOG", "Alphabet Inc. (Class C)", "XLC"),
    StockUniverseEntry("AVGO", "Broadcom", "SMH"),
    StockUniverseEntry("SPCX", "Space Exploration Technologies (SpaceX)", "ITA"),
    StockUniverseEntry("META", "Meta Platforms", "XLC"),
    StockUniverseEntry("TSLA", "Tesla, Inc.", "XLY"),
    StockUniverseEntry("MU", "Micron Technology", "SMH"),
    StockUniverseEntry("WMT", "Walmart", "XLP"),
    StockUniverseEntry("AMD", "Advanced Micro Devices", "SMH"),
    StockUniverseEntry("ASML", "ASML Holding", "SMH"),
    StockUniverseEntry("INTC", "Intel", "SMH"),
    StockUniverseEntry("CSCO", "Cisco", "XLK"),
    StockUniverseEntry("COST", "Costco", "XLP"),
    StockUniverseEntry("PLTR", "Palantir Technologies", "XLK"),
    StockUniverseEntry("LRCX", "Lam Research", "SMH"),
    StockUniverseEntry("AMAT", "Applied Materials", "SMH"),
    StockUniverseEntry("NFLX", "Netflix", "XLC"),
    StockUniverseEntry("PANW", "Palo Alto Networks", "XLK"),
    StockUniverseEntry("ARM", "Arm Holdings", "SMH"),
    StockUniverseEntry("KLAC", "KLA Corporation", "SMH"),
    StockUniverseEntry("TXN", "Texas Instruments", "SMH"),
    StockUniverseEntry("SNDK", "Sandisk", "XLK"),
    StockUniverseEntry("AMGN", "Amgen", "XLV"),
    StockUniverseEntry("LIN", "Linde plc", "XLB"),
    StockUniverseEntry("CRWD", "CrowdStrike", "XLK"),
    StockUniverseEntry("STX", "Seagate Technology", "XLK"),
    StockUniverseEntry("MRVL", "Marvell Technology", "SMH"),
    StockUniverseEntry("SHOP", "Shopify", "XLK"),
    StockUniverseEntry("TMUS", "T-Mobile US", "XLC"),
    StockUniverseEntry("PEP", "PepsiCo", "XLP"),
    StockUniverseEntry("ADI", "Analog Devices", "SMH"),
    StockUniverseEntry("WDC", "Western Digital", "XLK"),
    StockUniverseEntry("QCOM", "Qualcomm", "SMH"),
    StockUniverseEntry("GILD", "Gilead Sciences", "XLV"),
    StockUniverseEntry("BKNG", "Booking Holdings", "XLY"),
    StockUniverseEntry("ISRG", "Intuitive Surgical", "XLV"),
    StockUniverseEntry("VRTX", "Vertex Pharmaceuticals", "XLV"),
    StockUniverseEntry("SBUX", "Starbucks", "XLY"),
    StockUniverseEntry("PDD", "PDD Holdings", "XLY"),
    StockUniverseEntry("FTNT", "Fortinet", "XLK"),
    StockUniverseEntry("ABNB", "Airbnb", "XLY"),
    StockUniverseEntry("ADP", "Automatic Data Processing", "XLI"),
    StockUniverseEntry("APP", "AppLovin", "XLC"),
    StockUniverseEntry("ADBE", "Adobe Inc.", "XLK"),
    StockUniverseEntry("CEG", "Constellation Energy", "XLU"),
    StockUniverseEntry("INTU", "Intuit", "XLK"),
    StockUniverseEntry("DASH", "DoorDash", "XLY"),
    StockUniverseEntry("MELI", "MercadoLibre", "XLY"),
    StockUniverseEntry("MAR", "Marriott International", "XLY"),
    StockUniverseEntry("CSX", "CSX Corporation", "XLI"),
    StockUniverseEntry("CMCSA", "Comcast", "XLC"),
    StockUniverseEntry("DDOG", "Datadog", "XLK"),
    StockUniverseEntry("MNST", "Monster Beverage", "XLP"),
    StockUniverseEntry("CDNS", "Cadence Design Systems", "XLK"),
    StockUniverseEntry("REGN", "Regeneron Pharmaceuticals", "XLV"),
    StockUniverseEntry("LITE", "Lumentum Holdings", "XLK"),
    StockUniverseEntry("MDLZ", "Mondelez International", "XLP"),
    StockUniverseEntry("SNPS", "Synopsys", "XLK"),
    StockUniverseEntry("CTAS", "Cintas", "XLI"),
    StockUniverseEntry("ROST", "Ross Stores", "XLY"),
    StockUniverseEntry("NBIS", "Nebius Group", "XLK"),
    StockUniverseEntry("HON", "Honeywell International", "XLI"),
    StockUniverseEntry("ORLY", "O'Reilly Automotive", "XLY"),
    StockUniverseEntry("WBD", "Warner Bros. Discovery", "XLC"),
    StockUniverseEntry("MPWR", "Monolithic Power Systems", "SMH"),
    StockUniverseEntry("PCAR", "Paccar", "XLI"),
    StockUniverseEntry("AEP", "American Electric Power", "XLU"),
    StockUniverseEntry("TER", "Teradyne", "SMH"),
    StockUniverseEntry("BKR", "Baker Hughes", "XLE"),
    StockUniverseEntry("NXPI", "NXP Semiconductors", "SMH"),
    StockUniverseEntry("FAST", "Fastenal", "XLI"),
    StockUniverseEntry("CRWV", "CoreWeave", "XLK"),
    StockUniverseEntry("FANG", "Diamondback Energy", "XLE"),
    StockUniverseEntry("ALAB", "Astera Labs", "SMH"),
    StockUniverseEntry("ADSK", "Autodesk", "XLK"),
    StockUniverseEntry("PYPL", "PayPal", "XLF"),
    StockUniverseEntry("HONA", "Honeywell Aerospace", "ITA"),
    StockUniverseEntry("RKLB", "Rocket Lab Corporation", "ITA"),
    StockUniverseEntry("AXON", "Axon Enterprise", "ITA"),
    StockUniverseEntry("XEL", "Xcel Energy", "XLU"),
    StockUniverseEntry("WDAY", "Workday, Inc.", "XLK"),
    StockUniverseEntry("CCEP", "Coca-Cola Europacific Partners", "XLP"),
    StockUniverseEntry("EXC", "Exelon", "XLU"),
    StockUniverseEntry("FER", "Ferrovial", "XLI"),
    StockUniverseEntry("TTWO", "Take-Two Interactive", "XLC"),
    StockUniverseEntry("TRI", "Thomson Reuters", "XLC"),
    StockUniverseEntry("ODFL", "Old Dominion Freight Line", "XLI"),
    StockUniverseEntry("IDXX", "Idexx Laboratories", "XLV"),
    StockUniverseEntry("PAYX", "Paychex", "XLI"),
    StockUniverseEntry("MCHP", "Microchip Technology", "SMH"),
    StockUniverseEntry("KDP", "Keurig Dr Pepper", "XLP"),
    StockUniverseEntry("ROP", "Roper Technologies", "XLK"),
    StockUniverseEntry("MSTR", "Strategy (MicroStrategy)", "XLK"),
    StockUniverseEntry("DXCM", "Dexcom", "XLV"),
    StockUniverseEntry("GEHC", "GE HealthCare", "XLV"),
    StockUniverseEntry("ALNY", "Alnylam Pharmaceuticals", "XLV"),
    StockUniverseEntry("KHC", "Kraft Heinz", "XLP"),
    StockUniverseEntry("CPRT", "Copart", "XLI"),
    )

    val NASDAQ100: List<StockUniverseEntry> = rawNasdaq100.map { it.copy(indexName = MarketUniverse.NASDAQ100.indexName) }

    val ALL: List<StockUniverseEntry> = SP500 + NASDAQ100 + IBEX35
}
